[Variables]
@include=#@#Variables.inc

[UI]
Meter=Image
ImageName=images\health_inactive_female
MouseOverAction=!Execute [!ShowMeter ActiveUI][!ShowMeter ActiveSprite][!ShowMeter ActiveLabel][!ShowMeter ActiveMeterBatteryBar][!ShowMeter ActiveMeterDigit100][!ShowMeter ActiveMeterDigit010][!ShowMeter ActiveMeterDigit001][!HideMeter MeterDigit100][!HideMeter MeterDigit010][!HideMeter MeterDigit001][!HideMeter MeterBatteryBar][!HideMeter Sprite][!HideMeter UI][!HideMeter Label][!Update]

[ActiveUI]
Meter=Image
Hidden=1
ImageName=images\health_active_female
MouseLeaveAction=!Execute [!ShowMeter UI][!ShowMeter Sprite][!ShowMeter Label][!ShowMeter MeterBatteryBar][!ShowMeter MeterDigit100][!ShowMeter MeterDigit010][!ShowMeter MeterDigit001][!HideMeter ActiveMeterDigit100][!HideMeter ActiveMeterDigit010][!HideMeter ActiveMeterDigit001][!HideMeter ActiveMeterBatteryBar][!HideMeter ActiveLabel][!HideMeter ActiveSprite][!HideMeter ActiveUI][!Update]

[Label]
Meter=Image
ImageName=images\label_battery
x=62
y=10

[ActiveLabel]
Meter=Image
Hidden=1
ImageName=images\label_battery
x=62
y=12
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[MeasureBattery]
;Measure=Calc
;Formula=100
Measure=Plugin
Plugin=PowerPlugin
PowerState=Percent
IfCondition=(#CURRENTSECTION# <= 20)
IfTrueAction=[!SetOption MeterBatteryBar ImageName "#@#images\\percentage_20.png"][!SetOption ActiveMeterBatteryBar ImageName "#@#images\\percentage_20.png"][!UpdateMeter MeterBatteryBar][!UpdateMeter ActiveMeterBatteryBar][!Redraw]
IfCondition2=(#CURRENTSECTION# > 20) && (#CURRENTSECTION# <= 50)
IfTrueAction2=[!SetOption MeterBatteryBar ImageName "#@#images\\percentage_50.png"][!SetOption ActiveMeterBatteryBar ImageName "#@#images\\percentage_50.png"][!UpdateMeter MeterBatteryBar][!UpdateMeter ActiveMeterBatteryBar][!Redraw]
IfCondition3=(#CURRENTSECTION# > 50)
IfTrueAction3=[!SetOption MeterBatteryBar ImageName "#@#images\\percentage_100.png"][!SetOption ActiveMeterBatteryBar ImageName "#@#images\\percentage_100.png"][!UpdateMeter MeterBatteryBar][!UpdateMeter ActiveMeterBatteryBar][!Redraw]
DynamicVariables=1

[MeterBatteryBar]
Meter=Image
X=192
Y=16
W=(100 * [MeasureBattery]/100)
H=6
DynamicVariables=1

[ActiveMeterBatteryBar]
Meter=Image
Hidden=1
X=192
Y=18
W=(100 * [MeasureBattery]/100)
H=6
DynamicVariables=1

[Digit100]
Measure=Calc
Formula=Trunc([MeasureBattery]/100)
IfCondition=(#CURRENTSECTION# < 1)
IfTrueAction=[!SetOption MeterDigit100 MeasureName "blank.png"][!UpdateMeter MeterDigit100][!SetOption ActiveMeterDigit100 MeasureName "blank.png"][!UpdateMeter ActiveMeterDigit100][!Redraw]
DynamicVariables=1

[Digit010]
Measure=Calc
Formula=Floor(([MeasureBattery]-((Trunc([MeasureBattery]/100))*100))/10)
IfCondition=(#CURRENTSECTION# < 1) && ([Digit100] < 1)
IfTrueAction=[!SetOption MeterDigit010 MeasureName "blank.png"][!UpdateMeter MeterDigit010][!SetOption ActiveMeterDigit010 MeasureName "blank.png"][!UpdateMeter ActiveMeterDigit010][!Redraw]
DynamicVariables=1

[Digit001]
Measure=Calc
Formula=[MeasureBattery]%10
DynamicVariables=1

[MeterDigit100]
Meter=Image
MeasureName=Digit100
DynamicVariables=1
x=226
y=28

[MeterDigit010]
Meter=Image
MeasureName=Digit010
DynamicVariables=1
x=8r
y=0r

[MeterDigit001]
Meter=Image
MeasureName=Digit001
DynamicVariables=1
x=10r
y=0r

[ActiveMeterDigit100]
Meter=Image
Hidden=1
MeasureName=Digit100
DynamicVariables=1
x=226
y=30

[ActiveMeterDigit010]
Meter=Image
Hidden=1
MeasureName=Digit010
DynamicVariables=1
x=8r
y=0r

[ActiveMeterDigit001]
Meter=Image
Hidden=1
MeasureName=Digit001
DynamicVariables=1
x=10r
y=0r

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;Sprite
[Sprite]
Meter=Image
ImageName=images\025_pikachu_inactive.png
x=5
y=5
LeftMouseUpAction=["control.exe" /name Microsoft.PowerOptions]
ToolTipText=Left-click to open Power Options


[ActiveSprite]
Meter=Image
Hidden=1
ImageName=images\025_pikachu_active.png
x=6
y=6
LeftMouseUpAction=["control.exe" /name Microsoft.PowerOptions]
ToolTipText=Left-click to open Power Options

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[Rainmeter]
Update=1000

[Metadata]
Author = Paulina triplepants