[UI]
Meter=Image
ImageName=trainercard

[Variables]
@include=#@#Variables.inc

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;NAME = Username?
;11 letter limit
;replace each image name with letter in order
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[1stLetter]
Meter=Image
ImageName=P
x=108
y=84

[2ndLetter]
Meter=Image
ImageName=I
x=12r
y=0r

[3rdLetter]
Meter=Image
ImageName=N
x=12r
y=0r

[4thLetter]
Meter=Image
ImageName=K
x=12r
y=0r

[5thLetter]
Meter=Image
ImageName=A
x=12r
y=0r
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;Settings button: little star by name
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[SettingsImage]
Meter=Image
ImageName=images/star_settings
x=242
y=98

[SettingsImageAction]
Meter=Image
SolidColor=255,255,255,1
w=10
h=10
x=0r
y=0r
LeftMouseUpAction=[!ActivateConfig "Pokemon Trainer Card\Settings" "Settings.ini"]
ToolTipText=Left-click to open Settings
;#CRLF#Right-click TODO
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;ID No. = birthday?
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[1stNum]
Meter=Image
ImageName=1
x=320
y=38

[2ndNum]
Meter=Image
ImageName=0
;x=12r
x=8r
y=0r

[3rdNum]
Meter=Image
ImageName=0
;x=12r
x=10r
y=0r

[4thNum]
Meter=Image
ImageName=3
x=12r
y=0r

[5thNum]
Meter=Image
ImageName=9
x=12r
y=0r

[6thNum]
Meter=Image
ImageName=0
;x=12r
x=10r
y=0r
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;MONEY = Date
;NON-US Date format: ddmmyyyy
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[MoneySymbol]
Meter=Image
ImageName=money
x=131
y=132

;~~~~~~~~~~~~~~~
;DAY & MONTH
;~~~~~~~~~~~~~~~

[CurrentDay]
Measure=Time
Format=%d
;Format=%S


[Day10Measure]
Measure=Calc
Formula=Trunc(([CurrentDay] % 100) / 10)
DynamicVariables=1

[Day01Measure]
Measure=Calc
Formula=([CurrentDay] % 10)
DynamicVariables=1

[CurrentMonth]
Measure=Time
Format=%m

[Month10Measure]
Measure=Calc
Formula=Trunc(([CurrentMonth] % 100) / 10)
DynamicVariables=1

[Month01Measure]
Measure=Calc
Formula=([CurrentMonth] % 10)
DynamicVariables=1

;-----
;DRAW
;----- 
[Month10]
Meter=Image
MeasureName=Month10Measure
x=12r
y=0r

[Month01]
Meter=Image
MeasureName=Month01Measure
x=12r
y=0r 

[Day10]
Meter=Image
MeasureName=Day10Measure
x=12r
y=0r

[Day01]
Meter=Image
MeasureName=Day01Measure
x=11r
y=0r



;~~~~~~~~~~~~~~~
;YEAR
;~~~~~~~~~~~~~~~

[CurrentYear]
Measure=Time
Format=%Y

[Year1000]
Measure=Calc
Formula=Trunc([CurrentYear]/1000)
DynamicVariables=1

[Year0100]
Measure=Calc
Formula=Trunc(([CurrentYear] % 1000) / 100)
DynamicVariables=1

[Year0010]
Measure=Calc
Formula=Trunc(([CurrentYear] % 100) / 10)
DynamicVariables=1

[Year0001]
Measure=Calc
Formula=([CurrentYear]%10)
DynamicVariables=1

;-----
;DRAW
;-----

[Year1000Meter]
Meter=Image
MeasureName=Year1000
DynamicVariables=1
x=13r
y=0r

[Year0100Meter]
Meter=Image
MeasureName=Year0100
DynamicVariables=1
x=12r
y=0r

[Year0010Meter]
Meter=Image
MeasureName=Year0010
DynamicVariables=1
x=12r
y=0r

[Year0001Meter]
Meter=Image
MeasureName=Year0001
DynamicVariables=1
x=12r
y=0r
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;Pokedex = Recycling percentage left
;789 = empty (total amount of pokemon in ruby/sapphire)
;0 = full
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[MeasureTrash]
Measure=Plugin
Plugin=RecycleManager
MinValue=0
MaxValue=719
InvertMeasure=1

[TrashCanIcon]
Meter=Image
ImageName=trashcan
x=136
y=161
LeftMouseUpAction=[!CommandMeasure MeasureTrash "OpenBin"]
RightMouseUpAction=[!CommandMeasure MeasureTrash "EmptyBin"]
ToolTipText=Left-click to open#CRLF#Right-click to empty

[MeasureTrashHundreds]
Measure=Calc
Formula=Floor([MeasureTrash] / 100)
DynamicVariables=1

[MeasureTrashTens]
Measure=Calc
Formula=Floor(([MeasureTrash] % 100) / 10)
DynamicVariables=1

[MeasureTrashOnes]
Measure=Calc
Formula=Floor([MeasureTrash] % 10)
DynamicVariables=1

[DisplayMeasureTrashOnes]
Meter=Image
;ImageName=9
MeasureName=MeasureTrashOnes
x=227
y=164

[DisplayMeasureTrashTens]
Meter=Image
;ImageName=8
MeasureName=MeasureTrashTens
x=-12r
y=0r

[DisplayMeasureTrashHundreds]
Meter=Image
;ImageName=7
MeasureName=MeasureTrashHundreds
x=-12r
y=0r
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;PLAYTIME = CLOCK
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[CurrentHour]
Measure=Time
Format=%H

[HourTens]
Measure=Calc
Formula=Floor([CurrentHour]/10)
DynamicVariables=1

[HourOnes]
Measure=Calc
Formula=([CurrentHour]%10)
DynamicVariables=1

[CurrentMinute]
Measure=Time
Format=%M

[MinuteTens]
Measure=Calc
Formula=Floor([CurrentMinute]/10)
DynamicVariables=1

[MinuteOnes]
Measure=Calc
Formula=([CurrentMinute]%10)
DynamicVariables=1

[MeterHourTens]
Meter=Image
MeasureName=HourTens
;ImageName=0
DynamicVariables=1
x=179
y=196

[MeterHourOnes]
Meter=Image
MeasureName=HourOnes
;ImageName=0
DynamicVariables=1
x=12r
y=0r

[ToggleTimer]
Measure=Calc
Formula=(ToggleTimer + 1) % 2
UpdateDivider=1

[ToggleColon]
Meter=Image
ImageName=colon
;Hidden=0
x=12r
y=0r

;COMMENT OUT [ToggleImageVisibility] if you don't want flashing colon between hour and minutes
[ToggleImageVisibility]
Measure=Calc
Formula=[ToggleTimer]
IfEqualValue=0
IfEqualAction=[!HideMeter ToggleColon][!UpdateMeter ToggleColon][!Redraw]
IfAboveValue=0
IfAboveAction=[!ShowMeter ToggleColon][!UpdateMeter ToggleColon][!Redraw]
DynamicVariables=1

[MeterMinuteTens]
Meter=Image
MeasureName=MinuteTens
;ImageName=0
DynamicVariables=1
x=12r
y=0r

[MeterMinuteOnes]
Meter=Image
MeasureName=MinuteOnes
ImageName="#@#Images\[MinuteOnes].png"
DynamicVariables=1
x=12r
y=0r
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;Pokeball = an icon to click
;in this case takes me to a TODO folder
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[PokeballClick]
Meter=Image
SolidColor=255,255,255,1
w=36
h=24
x=235
y=36
;TO CHANGE THE ACTION ON LEFT CLICK CHANGE THE THING HERE
;EXAMPLE - [C:\WHATEVER\WHATEVER] OR [HTTPS:\\WWW.GOOGLE.COM\]
;LEAVE EMPTY FOR NO ACTION
LeftMouseUpAction=["D:\Dropbox\Askins\_TODO\WeightSchedule.xlsx"]
;LABEL WHAT MOUSE CLICKS DO
ToolTipText=Left-click to open Calorie Counter
;#CRLF#Right-click to empty

[PokeballIcon]
Meter=Image
;TO CHANGE THE ICON CHANGE THE NAME TO WHATEVER ITEM YOU WANT FROM THE FOLDER
;LEAVE EMPTY TO LEAVE TAB EMPTY
ImageName=masterball
x=6r
y=0r
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;BADGES = icons to press for different programs
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[Badge1Action]
Meter=Image
SolidColor=255,255,255,1
w=32
h=32
x=64
y=240
LeftMouseUpAction=["D:\Dropbox\"]
RightMouseUpAction=["D:\Dropbox\Askins\_TODO"]
ToolTipText=Left-click File Explorer#CRLF#Right-click TODO

[Badge1]
Meter=Image
ImageName=images\badges\#badge1#
;ImageName=stonebadge_colored
x=0r
y=0r

[Badge2Action]
Meter=Image
SolidColor=255,255,255,1
w=32
h=32
x=48r
y=0r
LeftMouseUpAction=["C:\Program Files (x86)\Steam\steam.exe"]
RightMouseUpAction=["D:\Dropbox\Askins\Emulators+Games"]
ToolTipText=Left-click Steam#CRLF#Right-click Emulators

[Badge2]
Meter=Image
ImageName=images\badges\#badge2#
;ImageName=knucklebadge_colored
x=0r
y=0r

[Badge3Action]
Meter=Image
SolidColor=255,255,255,1
w=32
h=32
x=48r
y=0r
LeftMouseUpAction=["%windir%\system32\notepad.exe"]
RightMouseUpAction=["C:\Program Files\Microsoft Office\root\Office16\WINWORD.exe"]
ToolTipText=Left-click Notepad#CRLF#Right-click Microsoft Word

[Badge3]
Meter=Image
ImageName=images\badges\#badge3#
;ImageName=dynamobadge_colored
x=0r
y=0r

[Badge4Action]
Meter=Image
SolidColor=255,255,255,1
w=32
h=32
x=48r
y=0r
LeftMouseUpAction=["C:\Users\paski\AppData\Local\Programs\Microsoft VS Code\Code.exe"]
RightMouseUpAction=["C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv.exe"]
ToolTipText=Left-click VS Code#CRLF#Right-click VS Community 2022

[Badge4]
Meter=Image
ImageName=images\badges\#badge4#
;ImageName=heatbadge_colored
x=0r
y=0r

[Badge5Action]
Meter=Image
SolidColor=255,255,255,1
w=32
h=32
x=48r
y=0r
LeftMouseUpAction=["C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"]
RightMouseUpAction=["C:\Users\paski\Desktop\Godot_v4.5.1-stable_win64.exe\Godot_v4.5.1-stable_win64.exe"]
ToolTipText=Left-click Chrome#CRLF#Right-click Godot
;#CRLF#Right-click TODO

[Badge5]
Meter=Image
ImageName=images\badges\#badge5#
;ImageName=balancebadge_colored
x=0r
y=0r

[Badge6Action]
Meter=Image
SolidColor=255,255,255,1
w=32
h=32
x=48r
y=0r
LeftMouseUpAction=["C:\Program Files\iTunes\iTunes.exe"]
RightMouseUpAction=["C:\Program Files (x86)\Audacity\audacity.exe"]
ToolTipText=Left-click iTunes#CRLF#Right-click Audacity

[Badge6]
Meter=Image
ImageName=images\badges\#badge6#
;ImageName=featherbadge_colored
x=0r
y=0r

[Badge7Action]
Meter=Image
SolidColor=255,255,255,1
w=32
h=32
x=48r
y=0r
LeftMouseUpAction=["C:\Windows\System32\calc.exe"]
RightMouseUpAction=["C:\Program Files\Tiled\tiled.exe"]
ToolTipText=Left-click Calculator#CRLF#Right-click Tiled

[Badge7]
Meter=Image
ImageName=images\badges\#badge7#
;ImageName=mindbadge_colored
x=0r
y=0r

[Badge8Action]
Meter=Image
SolidColor=255,255,255,1
w=32
h=32
x=48r
y=0r
LeftMouseUpAction=["C:\Program Files (x86)\Steam\steamapps\common\Aseprite\Aseprite.exe"]
RightMouseUpAction=["%windir%\system32\mspaint.exe"]
ToolTipText=Left-click Aseprite#CRLF#Right-click Paint

[Badge8]
Meter=Image
ImageName=images\badges\#badge8#
;ImageName=rainbadge_colored
x=0r
y=0r
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;SPRITE - simply cuteness and customization
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[SpriteDisplay]
Meter=Image
ImageName=images\sprites\sprite00
x=304
y=88
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;Setting button
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;[OpenSettingsButton]
;Meter=Image
;ImageName=YourButtonImage.png
;LeftMouseUpAction=[!ActivateConfig "YourSettingsSkinFolderName" "YourSettingsSkin.ini"]
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[Rainmeter]
Update=1000
WindowX=(#SCREENAREAWIDTH# - 480)
WindowY=0
KeepOnScreen=1

[Metadata]
Name=Pokémon Trainer Card
Author=Paulina (triplepants)