[Variables]
@include=#@#Variables.inc

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;Setup Box
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[MeterShape]
Meter=Shape
X=0
Y=0
Shape=Rectangle 0,0,480,304 | Fill Color 100,100,100,200 | Stroke Color #BackgroundColor#

[MeterLine]
Meter=Image
SolidColor=#BackgroundColor#
X=240
Y=0
W=1
H=304

[MeterLine2]
Meter=Image
SolidColor=#BackgroundColor#
X=240
Y=152
W=240
H=1

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;Text Settings
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[MeterSettingsText]
Meter=String
FontFace=#FontFace#
FontSize=20
FontColor=#ForegroundColor#
StringAlign=Left
StringCase=Upper
AntiAlias=1
X=50
Y=15
Text="Text Settings"

;-------------------------------------------------------------
;-------------------------------------------------------------
[MeasureUserName]
Measure=Plugin
Plugin=SysInfo
SysInfoType=USER_NAME
IfCondition=(MeasureUserName != "#UserName#")
IfTrueAction=[!WriteKeyValue Variables "UserName" "[MeasureUserName]" "#@#Variables.inc"][!RefreshGroup MyGroup]

[MeterNameAsk]
Meter=String
StringAlign=Left
FontColor=#ForegroundColor#
FontFace=#FontFace#
FontSize=12
X=20
Y=60
Text=Enter Name ->
AntiAlias=1

[MeterNameBar]
Meter=String
StringAlign=Left
FontFace=#FontFace#
FontColor=255,255,255
FontSize=12
X=130r
Y=0r
Text=#UserName#
AntiAlias=1
ToolTipText=Type name to display then press "Enter" (11 character limit)
LeftMouseUpAction=[!PluginBang "MeterNameInput ExecuteBatch 1"]

[MeterNameInput]
Measure=Plugin
Plugin=InputText.dll
X=151
Y=59
W=80
H=20
StringAlign=Left
FontFace=#FontFace#
AntiAlias=1
FontSize=12
FocusDismiss=1
Command1=[!WriteKeyValue Variables UserName "$UserInput$""#@#Variables.inc"][!RainmeterRefreshApp]
DefaultValue=#UserName#

;-------------------------------------------------------------
;-------------------------------------------------------------
[MeterBDayAsk]
Meter=String
StringAlign=Left
FontColor=#ForegroundColor#
FontFace=#FontFace#
FontSize=12
X=20
Y=20r
Text=Enter Birthday ->
AntiAlias=1

[MeterBDayBar]
Meter=String
StringAlign=Left
FontFace=#FontFace#
FontColor=255,255,255
FontSize=12
X=130r
Y=0r
Text=#Birthday#
AntiAlias=1
ToolTipText=Type birthday in format MMDDYY then press "Enter"
LeftMouseUpAction=[!PluginBang "MeterBDayInput ExecuteBatch 1"]

[MeterBDayInput]
Measure=Plugin
Plugin=InputText.dll
X=151
Y=80
W=80
H=20
StringAlign=Left
FontFace=#FontFace#
AntiAlias=1
FontSize=12
FocusDismiss=1
Command1=[!WriteKeyValue Variables Birthday "$UserInput$""#@#Variables.inc"][!RainmeterRefreshApp]
DefaultValue=#Birthday#

;-------------------------------------------------------------
;-------------------------------------------------------------
[MeterSpriteAsk]
Meter=String
StringAlign=Left
FontColor=#ForegroundColor#
FontFace=#FontFace#
FontSize=12
X=20
Y=20r
Text=Enter Sprite Name ->
AntiAlias=1

[MeterSpriteBar]
Meter=String
StringAlign=Left
FontFace=#FontFace#
FontColor=255,255,255
FontSize=12
X=130r
Y=0r
Text=#Sprite#
AntiAlias=1
ToolTipText=Type sprite name from  then press "Enter"
LeftMouseUpAction=[!PluginBang "MeterSpriteInput ExecuteBatch 1"]

[MeterSpriteInput]
Measure=Plugin
Plugin=InputText.dll
X=151
Y=100
W=80
H=20
StringAlign=Left
FontFace=#FontFace#
AntiAlias=1
FontSize=12
FocusDismiss=1
Command1=[!WriteKeyValue Variables Sprite "$UserInput$""#@#Variables.inc"][!RainmeterRefreshApp]
DefaultValue=#Sprite#

;-------------------------------------------------------------
;-------------------------------------------------------------

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;Badges Settings
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[1stBadge]
Meter=String
Text= "1st Badge"
FontFace=#FontFace#
FontSize=13
FontWeight=700
FontColor=#BackgroundColor#
;SolidColor=0,0,0,255
x=20
y=30r
Padding=3,3,3,3
;LeftMouseUpAction=[!ToggleMeter Option1][!ToggleMeter Option2][!UpdateMeterGroup Options][!Redraw]
MouseOverAction=!Execute [!ShowMeter Option1][!ShowMeter Option2][!Update]
;MouseLeaveAction=!Execute [!HideMeter Option1][!HideMeter Option2][!Update]

[5thBadge]
Meter=String
Text= "5th Badge"
FontFace=#FontFace#
FontSize=13
FontWeight=700
FontColor=#BackgroundColor#
;SolidColor=0,0,0,255
x=100r
y=0r
Padding=3,3,3,3
;LeftMouseUpAction=[!ToggleMeter Option1][!ToggleMeter Option2][!UpdateMeterGroup Options][!Redraw]
MouseOverAction=!Execute [!ShowMeter Option1][!ShowMeter Option2][!Update]
;MouseLeaveAction=!Execute [!HideMeter Option1][!HideMeter Option2][!Update]

[2ndBadge]
Meter=String
Text= "2nd Badge"
FontFace=#FontFace#
FontSize=13
FontWeight=700
FontColor=#BackgroundColor#
;SolidColor=0,0,0,255
x=-100r
y=30r
Padding=3,3,3,3
;LeftMouseUpAction=[!ToggleMeter Option1][!ToggleMeter Option2][!UpdateMeterGroup Options][!Redraw]
MouseOverAction=!Execute [!ShowMeter Option1][!ShowMeter Option2][!Update]
;MouseLeaveAction=!Execute [!HideMeter Option1][!HideMeter Option2][!Update]

[6thBadge]
Meter=String
Text= "6th Badge"
FontFace=#FontFace#
FontSize=13
FontWeight=700
FontColor=#BackgroundColor#
;SolidColor=0,0,0,255
x=100r
y=0r
Padding=3,3,3,3
;LeftMouseUpAction=[!ToggleMeter Option1_1][!ToggleMeter Option2_1][!UpdateMeterGroup Options][!Redraw]
MouseOverAction=!Execute [!ShowMeter Option1_1][!ShowMeter Option2_1][!Update]
;MouseLeaveAction=!Execute [!HideMeter Option1_1][!HideMeter Option2_1][!Update]

;First Badge: Option 1
[Option1_1]
Meter=String
MeterStyle=OptionStyle
Text="Stone Badge"
FontFace=#FontFace#
FontSize=15
Y=30r
Group=Options
Hidden=1
LeftMouseUpAction=[!WriteKeyValue Variables badge1 "stonebadge" "#@#Variables.inc"][!Refresh *]
;MouseOverAction=!Execute [!ShowMeter 1stBadge][!ShowMeter Option1][!ShowMeter Option2][!Update]
;MouseLeaveAction=!Execute [!HideMeter Option1][!HideMeter Option2][!Update]

;First Badge: Option 2
[Option2_1]
Meter=String
MeterStyle=OptionStyle
Text="Knuckle Badge"
FontFace=#FontFace#
FontSize=15
Y=30r
Group=Options
Hidden=1
LeftMouseUpAction=[!WriteKeyValue Variables badge1 "knucklebadge" "#@#Variables.inc"][!Refresh *]
;MouseOverAction=!Execute [!ShowMeter 1stBadge][!ShowMeter Option1][!ShowMeter Option2][!Update]
;MouseLeaveAction=!Execute [!HideMeter Option1][!HideMeter Option2][!Update]


; Style for Options
[OptionStyle]
FontSize=13
FontColor=255,255,255,255
SolidColor=50,50,50,255
Padding=5,5,5,5
AntiAlias=1


;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;Color Settings
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[MeterBackgroundColorsText]
Meter=String
FontFace=#FontFace#
FontSize=20
FontColor=#ForegroundColor#
StringAlign=Left
StringCase=Upper
AntiAlias=1
X=265
Y=15
Text="Background Color"

[MeterColor1]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=287
Y=55
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables BackgroundColor "255,255,255" "#@#Variables.inc"][!Refresh *]
ImageTint=255,255,255
ToolTipText="Click here to change background color"

[MeterColor2]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=31r
Y=r
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables BackgroundColor "0,0,0" "#@#Variables.inc"][!Refresh *]
ImageTint=0,0,0
ToolTipText="Click here to change background color"

[MeterColor3]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=31r
Y=r
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables BackgroundColor "255,204,0" "#@#Variables.inc"][!Refresh *]
ImageTint=255,255,0
ToolTipText="Click here to change background color"

[MeterColor4]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=31r
Y=r
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables BackgroundColor "255,153,0" "#@#Variables.inc"][!Refresh *]
ImageTint=255,153,0
ToolTipText="Click here to change background color"

[MeterColor5]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=31r
Y=r
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables BackgroundColor "255,102,0" "#@#Variables.inc"][!Refresh *]
ImageTint=255,102,0
ToolTipText="Click here to change background color"

[MeterColor6]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=287
Y=30r
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables BackgroundColor "204,0,0" "#@#Variables.inc"][!Refresh *]
ImageTint=204,0,0
ToolTipText="Click here to change background color"

[MeterColor7]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=31r
Y=r
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables BackgroundColor "153,0,0" "#@#Variables.inc"][!Refresh *]
ImageTint=153,0,0
ToolTipText="Click here to change background color"

[MeterColor8]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=31r
Y=r
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables BackgroundColor "204,102,153" "#@#Variables.inc"][!Refresh *]
ImageTint=204,102,153
ToolTipText="Click here to change background color"

[MeterColor9]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=31r
Y=r
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables BackgroundColor "255,0,153" "#@#Variables.inc"][!Refresh *]
ImageTint=255,0,153
ToolTipText="Click here to change background color"

[MeterColor10]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=31r
Y=r
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables BackgroundColor "153,0,255" "#@#Variables.inc"][!Refresh *]
ImageTint=153,0,255
ToolTipText="Click here to change background color"

[MeterColor11]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=287
Y=30r
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables BackgroundColor "153,204,0" "#@#Variables.inc"][!Refresh *]
ImageTint=153,204,0
ToolTipText="Click here to change background color"

[MeterColor12]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=31r
Y=r
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables BackgroundColor "51,153,0" "#@#Variables.inc"][!Refresh *]
ImageTint=51,153,0
ToolTipText="Click here to change background color"

[MeterColor13]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=31r
Y=r
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables BackgroundColor "36,255,0" "#@#Variables.inc"][!Refresh *]
ImageTint=36,255,0
ToolTipText="Click here to change background color"

[MeterColor14]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=31r
Y=r
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables BackgroundColor "2,95,255" "#@#Variables.inc"][!Refresh *]
ImageTint=2,95,255
ToolTipText="Click here to change background color"

[MeterColor15]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=31r
Y=r
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables BackgroundColor "2,238,251" "#@#Variables.inc"][!Refresh *]
ImageTint=2,238,251
ToolTipText="Click here to change background color"

;Foreground
[MeterForegroundColorsText]
Meter=String
FontFace=#FontFace#
FontSize=20
FontColor=#ForegroundColor#
StringAlign=Left
StringCase=Upper
AntiAlias=1
X=265
Y=165
Text="Foreground Color"

[MeterColor16]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=287
Y=205
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables ForegroundColor "255,255,255" "#@#Variables.inc"][!Refresh *]
ImageTint=255,255,255
ToolTipText="Click here to change foreground color"

[MeterColor17]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=31r
Y=r
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables ForegroundColor "0,0,0" "#@#Variables.inc"][!Refresh *]
ImageTint=0,0,0
ToolTipText="Click here to change foreground color"

[MeterColor18]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=31r
Y=r
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables ForegroundColor "255,204,0" "#@#Variables.inc"][!Refresh *]
ImageTint=255,255,0
ToolTipText="Click here to change foreground color"

[MeterColor19]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=31r
Y=r
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables ForegroundColor "255,153,0" "#@#Variables.inc"][!Refresh *]
ImageTint=255,153,0
ToolTipText="Click here to change foreground color"

[MeterColor20]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=31r
Y=r
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables ForegroundColor "255,102,0" "#@#Variables.inc"][!Refresh *]
ImageTint=255,102,0
ToolTipText="Click here to change foreground color"

[MeterColor21]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=287
Y=30r
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables ForegroundColor "204,0,0" "#@#Variables.inc"][!Refresh *]
ImageTint=204,0,0
ToolTipText="Click here to change foreground color"

[MeterColor22]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=31r
Y=r
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables ForegroundColor "153,0,0" "#@#Variables.inc"][!Refresh *]
ImageTint=153,0,0
ToolTipText="Click here to change foreground color"

[MeterColor23]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=31r
Y=r
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables ForegroundColor "204,102,153" "#@#Variables.inc"][!Refresh *]
ImageTint=204,102,153
ToolTipText="Click here to change foreground color"

[MeterColor25]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=31r
Y=r
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables ForegroundColor "255,0,153" "#@#Variables.inc"][!Refresh *]
ImageTint=255,0,153
ToolTipText="Click here to change foreground color"

[MeterColor26]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=31r
Y=r
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables ForegroundColor "153,0,255" "#@#Variables.inc"][!Refresh *]
ImageTint=153,0,255
ToolTipText="Click here to change foreground color"

[MeterColor27]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=287
Y=30r
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables ForegroundColor "153,204,0" "#@#Variables.inc"][!Refresh *]
ImageTint=153,204,0
ToolTipText="Click here to change foreground color"

[MeterColor28]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=31r
Y=r
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables ForegroundColor "51,153,0" "#@#Variables.inc"][!Refresh *]
ImageTint=51,153,0
ToolTipText="Click here to change foreground color"

[MeterColor29]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=31r
Y=r
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables ForegroundColor "36,255,0" "#@#Variables.inc"][!Refresh *]
ImageTint=36,255,0
ToolTipText="Click here to change foreground color"

[MeterColor30]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=31r
Y=r
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables ForegroundColor "2,95,255" "#@#Variables.inc"][!Refresh *]
ImageTint=2,95,255
ToolTipText="Click here to change foreground color"

[MeterColor31]
Meter=IMAGE
ImageName=#@#ColorBox.png
X=31r
Y=r
W=20
LeftMouseUpAction=!Execute [!WriteKeyValue Variables ForegroundColor "2,238,251" "#@#Variables.inc"][!Refresh *]
ImageTint=2,238,251
ToolTipText="Click here to change foreground color"

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;Close Settings
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[MeterCloseButtonPassive]
Meter=String
StringAlign=Left
FontFace=#FontFace#
FontSize=15
FontColor=#ForegroundColor#
X=60
Y=10r
Text=Close Settings
SolidColor=0,0,0,1
AntiAlias=1
MouseOverAction=!Execute [!ShowMeter MeterCloseButtonActive][!HideMeter MeterCloseButtonPassive][!Update]

[MeterCloseButtonActive]
Meter=String
StringAlign=Left
FontFace=#FontFace#
FontSize=15
FontWeight=800
FontColor=255,255,255
X=r
Y=r
Text=> Close Settings
SolidColor=0,0,0,1
AntiAlias=1
Hidden=1
InlineSetting=Shadow | 0 | 0 | 4.5 | 254,255,214
LeftMouseUpAction=[!DeactivateConfig "Pokemon Trainer Card\Settings" "settings.ini"][!ShowMeter MeterCloseButtonPassive][!HideMeter MeterCloseButtonActive][!Update]
MouseLeaveAction=!Execute [!ShowMeter MeterCloseButtonPassive][!HideMeter MeterCloseButtonActive][!Update]


[Rainmeter]
Update=1000
WindowX=(#SCREENAREAWIDTH# - 480)
WindowY=0
KeepOnScreen=1

[Metadata]
Name=Pokémon Trainer Card Settings
Author=Paulina (triplepants)