[Settings]
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;Trainer Info

UserName=YOUR_USERNAME
;MonthDayYear (or whatever format you prefer but only numbers)
Birthday=010102001

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;File Path Info

VSCodePath=C:\Users\YOUR_USERNAME\AppData\Local\Programs\Microsoft VS Code\Code.exe
CalculatorPath=C:\Windows\System32\calc.exe
;etc.