[Settings]
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;Trainer Info

UserName=YOUR_USERNAME
;MonthDayYear (or whatever format you prefer but only numbers)
Birthday=010102001

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;File Path Info

Badge1LeftClickPath=C:\Path\To\Program01.exe
Badge1RightClickPath=C:\Path\To\Folder

Badge2LeftClicPathk=C:\Path\To\File.fileExtension
;if you have nothing to link it to just leave blank
Badge2RightClickPath=

;add all the other badges (up to 8)

MasterballPath=C:\Path\To\Your\File.extention

