[Variables]
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;Card Settings
Language = English

BackgroundColor=255,204,0
ForegroundColor=0,0,0

CardX=0
CardY=0

;FontColor=2,238,251
;FontFace=Gill Sans MT Condensed
;FontFace=Arial
FontFace=Agency FB

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;Trainer Info

UserName=Pinka
Birthday=10031990

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;Badges
badge1=stonebadge
badge2=knucklebadge
badge3=rainbowbadge
badge4=heatbadge
badge5=balancebadge
badge6=featherbadge
badge7=mindbadge
badge8=rainbadge

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;Sprite
Sprite=sprite00

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;System Info
BatteryPercentage=1
