[UI]
Meter=Image
ImageName=trainercard

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;NAME = Username?
;11 letter limit
;replace each image name with letter in order
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[1stLetter]
Meter=Image
ImageName=P
x=108
y=84

[2ndLetter]
Meter=Image
ImageName=I
x=12r
y=0r

[3rdLetter]
Meter=Image
ImageName=N
x=12r
y=0r

[4thLetter]
Meter=Image
ImageName=K
x=12r
y=0r

[5thLetter]
Meter=Image
ImageName=A
x=12r
y=0r

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;ID No. = birthday?
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[1stNum]
Meter=Image
ImageName=1
x=320
y=38

[2ndNum]
Meter=Image
ImageName=0
;x=12r
x=8r
y=0r

[3rdNum]
Meter=Image
ImageName=0
;x=12r
x=10r
y=0r

[4thNum]
Meter=Image
ImageName=3
x=12r
y=0r

[5thNum]
Meter=Image
ImageName=9
x=12r
y=0r

[6thNum]
Meter=Image
ImageName=0
;x=12r
x=10r
y=0r
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;MONEY = Date
;NON-US Date format: ddmmyyyy
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[MoneySymbol]
Meter=Image
ImageName=money
x=131
y=132

[Day10]
Meter=Image
DynamicVariables=1
x=12r
y=0r

[Day01]
Meter=Image
DynamicVariables=1
x=12r
y=0r

[Month10]
Meter=Image
DynamicVariables=1
x=12r
y=0r

[Month01]
Meter=Image
DynamicVariables=1
x=12r
y=0r

;~~~~~~~~~~~DAY~~~~~~~~~~~
[FullDateDay]
Measure=Time
Format=%d
IfMatch=1
IfMatchAction=[!SetOption Day10 ImageName 0][!SetOption Day01 ImageName 1][!Redraw]
IfMatch2=2
IfMatchAction2=[!SetOption Day10 ImageName 0][!SetOption Day01 ImageName 2][!Redraw]
IfMatch3=3
IfMatchAction3=[!SetOption Day10 ImageName 0][!SetOption Day01 ImageName 3][!Redraw]
IfMatch4=4
IfMatchAction4=[!SetOption Day10 ImageName 0][!SetOption Day01 ImageName 4][!Redraw]
IfMatch5=5
IfMatchAction5=[!SetOption Day10 ImageName 0][!SetOption Day01 ImageName 5][!Redraw]
IfMatch6=6
IfMatchAction6=[!SetOption Day10 ImageName 0][!SetOption Day01 ImageName 6][!Redraw]
IfMatch7=7
IfMatchAction7=[!SetOption Day10 ImageName 0][!SetOption Day01 ImageName 7][!Redraw]
IfMatch8=8
IfMatchAction8=[!SetOption Day10 ImageName 0][!SetOption Day01 ImageName 8][!Redraw]
IfMatch9=9
IfMatchAction9=[!SetOption Day10 ImageName 0][!SetOption Day01 ImageName 9][!Redraw]
IfMatch10=10
IfMatchAction10=[!SetOption Day10 ImageName 1][!SetOption Day01 ImageName 0][!Redraw]
IfMatch11=11
IfMatchAction11=[!SetOption Day10 ImageName 1][!SetOption Day01 ImageName 1][!Redraw]
IfMatch12=12
IfMatchAction12=[!SetOption Day10 ImageName 1][!SetOption Day01 ImageName 2][!Redraw]
IfMatch13=13
IfMatchAction13=[!SetOption Day10 ImageName 1][!SetOption Day01 ImageName 3][!Redraw]
IfMatch14=14
IfMatchAction14=[!SetOption Day10 ImageName 1][!SetOption Day01 ImageName 4][!Redraw]
IfMatch15=15
IfMatchAction15=[!SetOption Day10 ImageName 1][!SetOption Day01 ImageName 5][!Redraw]
IfMatch16=16
IfMatchAction16=[!SetOption Day10 ImageName 1][!SetOption Day01 ImageName 6][!Redraw]
IfMatch17=17
IfMatchAction17=[!SetOption Day10 ImageName 1][!SetOption Day01 ImageName 7][!Redraw]
IfMatch18=18
IfMatchAction18=[!SetOption Day10 ImageName 1][!SetOption Day01 ImageName 8][!Redraw]
IfMatch19=19
IfMatchAction19=[!SetOption Day10 ImageName 1][!SetOption Day01 ImageName 9][!Redraw]
IfMatch20=20
IfMatchAction20=[!SetOption Day10 ImageName 2][!SetOption Day01 ImageName 0][!Redraw]
IfMatch21=21
IfMatchAction21=[!SetOption Day10 ImageName 2][!SetOption Day01 ImageName 1][!Redraw]
IfMatch22=22
IfMatchAction22=[!SetOption Day10 ImageName 2][!SetOption Day01 ImageName 2][!Redraw]
IfMatch23=23
IfMatchAction23=[!SetOption Day10 ImageName 2][!SetOption Day01 ImageName 3][!Redraw]
IfMatch24=24
IfMatchAction24=[!SetOption Day10 ImageName 2][!SetOption Day01 ImageName 4][!Redraw]
IfMatch25=25
IfMatchAction25=[!SetOption Day10 ImageName 2][!SetOption Day01 ImageName 5][!Redraw]
IfMatch26=26
IfMatchAction26=[!SetOption Day10 ImageName 2][!SetOption Day01 ImageName 6][!Redraw]
IfMatch27=27
IfMatchAction27=[!SetOption Day10 ImageName 2][!SetOption Day01 ImageName 7][!Redraw]
IfMatch28=28
IfMatchAction28=[!SetOption Day10 ImageName 2][!SetOption Day01 ImageName 8][!Redraw]
IfMatch29=29
IfMatchAction29=[!SetOption Day10 ImageName 2][!SetOption Day01 ImageName 9][!Redraw]
IfMatch30=30
IfMatchAction30=[!SetOption Day10 ImageName 3][!SetOption Day01 ImageName 0][!Redraw]
IfMatch31=31
IfMatchAction31=[!SetOption Day10 ImageName 3][!SetOption Day01 ImageName 1][!Redraw]

;~~~~~~~~~~~MONTH~~~~~~~~~~~
[FullDateMonth]
Measure=Time
Format=%#m
IfMatch=1
IfMatchAction=[!SetOption Month10 ImageName 0][!SetOption Month01 ImageName 1][!Redraw]
IfMatch2=2
IfMatchAction2=[!SetOption Month10 ImageName 0][!SetOption Month01 ImageName 2][!Redraw]
IfMatch3=3
IfMatchAction3=[!SetOption Month10 ImageName 0][!SetOption Month01 ImageName 3][!Redraw]
IfMatch4=4
IfMatchAction4=[!SetOption Month10 ImageName 0][!SetOption Month01 ImageName 4][!Redraw]
IfMatch5=5
IfMatchAction5=[!SetOption Month10 ImageName 0][!SetOption Month01 ImageName 5][!Redraw]
IfMatch6=6
IfMatchAction6=[!SetOption Month10 ImageName 0][!SetOption Month01 ImageName 6][!Redraw]
IfMatch7=7
IfMatchAction7=[!SetOption Month10 ImageName 0][!SetOption Month01 ImageName 7][!Redraw]
IfMatch8=8
IfMatchAction8=[!SetOption Month10 ImageName 0][!SetOption Month01 ImageName 8][!Redraw]
IfMatch9=9
IfMatchAction9=[!SetOption Month10 ImageName 0][!SetOption Month01 ImageName 9][!Redraw]
IfMatch10=10
IfMatchAction10=[!SetOption Month10 ImageName 1][!SetOption Month01 ImageName 0][!Redraw]
IfMatch11=11
IfMatchAction11=[!SetOption Month10 ImageName 1][!SetOption Month01 ImageName 1][!Redraw]
IfMatch12=12
IfMatchAction12=[!SetOption Month10 ImageName 1][!SetOption Month01 ImageName 2][!Redraw]

;~~~~~~~~~~~YEAR~~~~~~~~~~~
[CurrentYear]
Measure=Time
Format=%Y

[Year1000]
Measure=Calc
Formula=Trunc([CurrentYear]/1000)
DynamicVariables=1

[Year0100]
Measure=Calc
Formula=([CurrentYear]-((Trunc([CurrentYear]/1000))*1000))/100
DynamicVariables=1

[Year0010]
Measure=Calc
Formula=([CurrentYear]-((Trunc([CurrentYear]/1000))*1000))/10
DynamicVariables=1

[Year0001]
Measure=Calc
Formula=([CurrentYear]%10)
DynamicVariables=1

[Year1000Meter]
Meter=Image
MeasureName=Year1000
DynamicVariables=1
x=12r
y=0r

[Year0100Meter]
Meter=Image
MeasureName=Year0100
DynamicVariables=1
x=12r
y=0r

[Year0010Meter]
Meter=Image
MeasureName=Year0010
DynamicVariables=1
x=12r
y=0r

[Year0001Meter]
Meter=Image
MeasureName=Year0001
DynamicVariables=1
x=12r
y=0r
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;Pokedex = Recycling percentage left
;100 = empty
;0 = full
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[MeasureTrash]
Measure=Plugin
Plugin=RecycleManager
MinValue=0
MaxValue=719
InvertMeasure=1

[TrashCanIcon]
Meter=Image
ImageName=trashcan
x=136
y=161
LeftMouseUpAction=[!CommandMeasure MeasureTrash "OpenBin"]
RightMouseUpAction=[!CommandMeasure MeasureTrash "EmptyBin"]
ToolTipText=Left-click to open#CRLF#Right-click to empty

[TrashPercentageOnes]
Meter=Calc
Formula=[MeasureTrash]

[TrashPercentageTens]
Meter=Calc
Formula=Floor([MeasureTrash]/100)

[TrashPercentageHundreds]
Meter=Calc
Formula=Floor([MeasureTrash]/100)

[DisplayTrashPercentageOnes]
Meter=Image
ImageName=9
;MeasureName=MeasureTrash
x=227
y=164

[DisplayTrashPercentageTens]
Meter=Image
ImageName=8
;MeasureName=1
x=-12r
y=0r

[DisplayTrashPercentageHundreds]
Meter=Image
ImageName=7
MeasureName=TrashPercentageHundreds
x=-12r
y=0r

;*******************************************************************
;TEST
[TestString]
Meter=String
MeasureName=MeasureTrash
;MeasureName=TrashPercentageOnes
;MeasureName=TrashPercentageTens
;MeasureName=TrashPercentageHundreds
X=0r
Y=50r
FontColor=100,100,100,100
FontSize=20
AntiAlias=1
Text="Trash: %1"
;*******************************************************************
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;PLAYTIME = CLOCK
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[CurrentHour]
Measure=Time
Format=%H

[HourTens]
Measure=Calc
Formula=Floor([CurrentHour]/10)
DynamicVariables=1

[HourOnes]
Measure=Calc
Formula=([CurrentHour]%10)
DynamicVariables=1

[CurrentMinute]
Measure=Time
Format=%M

[MinuteTens]
Measure=Calc
Formula=Floor([CurrentMinute]/10)
DynamicVariables=1

[MinuteOnes]
Measure=Calc
Formula=([CurrentMinute]%10)
DynamicVariables=1

[MeterHourTens]
Meter=Image
MeasureName=HourTens
;ImageName=0
DynamicVariables=1
x=179
y=196

[MeterHourOnes]
Meter=Image
MeasureName=HourOnes
;ImageName=0
DynamicVariables=1
x=12r
y=0r

[ToggleTimer]
Measure=Calc
Formula=(ToggleTimer + 1) % 2
UpdateDivider=1

;*******************************************************************
;TEST
;[ToggleTimeString]
;Meter=String
;MeasureName=ToggleTimer
;X=10r
;Y=0r
;FontColor=100,100,100,100
;FontSize=20
;AntiAlias=1
;Text="Toggle Timer: %1"
;*******************************************************************

[ToggleColon]
Meter=Image
ImageName=colon
;Hidden=0
x=12r
y=0r

;COMMENT OUT [ToggleImageVisibility] if you don't want flashing colon between hour and minutes
[ToggleImageVisibility]
Measure=Calc
Formula=[ToggleTimer]
IfEqualValue=0
IfEqualAction=[!HideMeter ToggleColon][!UpdateMeter ToggleColon][!Redraw]
IfAboveValue=0
IfAboveAction=[!ShowMeter ToggleColon][!UpdateMeter ToggleColon][!Redraw]
DynamicVariables=1

[MeterMinuteTens]
Meter=Image
MeasureName=MinuteTens
;ImageName=0
DynamicVariables=1
x=12r
y=0r

[MeterMinuteOnes]
Meter=Image
MeasureName=MinuteOnes
ImageName="#@#Images\[MinuteOnes].png"
DynamicVariables=1
x=12r
y=0r

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;Pokeball = an icon to click
;in this case takes me to a TODO folder
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[PokeballClick]
Meter=Image
SolidColor=255,255,255,1
w=36
h=24
x=235
y=36
;TO CHANGE THE ACTION ON LEFT CLICK CHANGE THE THING HERE
;EXAMPLE - [C:\WHATEVER\WHATEVER] OR [HTTPS:\\WWW.GOOGLE.COM\]
;LEAVE EMPTY FOR NO ACTION
LeftMouseUpAction=["D:\Dropbox\Askins\_TODO"]
;LABEL WHAT MOUSE CLICKS DO
ToolTipText=Left-click to open TODO
;#CRLF#Right-click to empty

[PokeballIcon]
Meter=Image
;TO CHANGE THE ICON CHANGE THE NAME TO WHATEVER ITEM YOU WANT FROM THE FOLDER
;LEAVE EMPTY TO LEAVE TAB EMPTY
ImageName=masterball
x=6r
y=0r
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;BADGES = icons to press for different programs
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[Badge1Action]
Meter=Image
SolidColor=255,255,255,1
w=32
h=32
x=64
y=240
LeftMouseUpAction=["D:\Dropbox\"]
RightMouseUpAction=["D:\Dropbox\Askins\_TODO"]
ToolTipText=Left-click File Explorer#CRLF#Right-click TODO

[Badge1]
Meter=Image
ImageName=stonebadge_colored
x=0r
y=0r

[Badge2Action]
Meter=Image
SolidColor=255,255,255,1
w=32
h=32
x=48r
y=0r
LeftMouseUpAction=["C:\Program Files (x86)\Steam\steam.exe"]
;RightMouseUpAction=["D:\Dropbox\Askins\_TODO"]
ToolTipText=Left-click Steam
;#CRLF#Right-click TODO

[Badge2]
Meter=Image
ImageName=knucklebadge_colored
x=0r
y=0r

[Badge3Action]
Meter=Image
SolidColor=255,255,255,1
w=32
h=32
x=48r
y=0r
LeftMouseUpAction=["%windir%\system32\notepad.exe"]
RightMouseUpAction=["C:\Program Files\Microsoft Office\root\Office16\WINWORD.exe"]
ToolTipText=Left-click Notepad#CRLF#Right-click Microsoft Word

[Badge3]
Meter=Image
ImageName=dynamobadge_colored
x=0r
y=0r

[Badge4Action]
Meter=Image
SolidColor=255,255,255,1
w=32
h=32
x=48r
y=0r
LeftMouseUpAction=["C:\Users\paski\AppData\Local\Programs\Microsoft VS Code\Code.exe"]
RightMouseUpAction=["C:\Program Files\Unity Hub\Unity Hub.exe"]
ToolTipText=Left-click VS Code#CRLF#Right-click Unity

[Badge4]
Meter=Image
ImageName=heatbadge_colored
x=0r
y=0r

[Badge5Action]
Meter=Image
SolidColor=255,255,255,1
w=32
h=32
x=48r
y=0r
LeftMouseUpAction=["C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"]
;RightMouseUpAction=["D:\Dropbox\Askins\_TODO"]
ToolTipText=Left-click Chrome
;#CRLF#Right-click TODO

[Badge5]
Meter=Image
ImageName=balancebadge_colored
x=0r
y=0r

[Badge6Action]
Meter=Image
SolidColor=255,255,255,1
w=32
h=32
x=48r
y=0r
LeftMouseUpAction=["C:\Program Files\iTunes\iTunes.exe]
RightMouseUpAction=["C:\Program Files (x86)\Audacity\audacity.exe"]
ToolTipText=Left-click iTunes#CRLF#Right-click Audacity

[Badge6]
Meter=Image
ImageName=featherbadge_colored
x=0r
y=0r

[Badge7Action]
Meter=Image
SolidColor=255,255,255,1
w=32
h=32
x=48r
y=0r
LeftMouseUpAction=["C:\Windows\System32\calc.exe"]
;RightMouseUpAction=["D:\Dropbox\Askins\_TODO"]
ToolTipText=Left-click Calculator
;#CRLF#Right-click TODO

[Badge7]
Meter=Image
ImageName=mindbadge_colored
x=0r
y=0r

[Badge8Action]
Meter=Image
SolidColor=255,255,255,1
w=32
h=32
x=48r
y=0r
LeftMouseUpAction=["C:\Program Files (x86)\Steam\steamapps\common\Aseprite\Aseprite.exe"]
RightMouseUpAction=["%windir%\system32\mspaint.exe"]
ToolTipText=Left-click Aseprite#CRLF#Right-click Paint

[Badge8]
Meter=Image
ImageName=rainbadge_colored
x=0r
y=0r
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;SPRITE - simply cuteness and customization
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[SpriteDisplay]
Meter=Image
ImageName=sprite00
x=304
y=88
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[Rainmeter]
Update=1000

[Metadata]
Name=Pokémon Trainer Card
Author=Paulina