[Variables]
@include=#@#Variables.inc

[UI]
Meter=Image
ImageName=..\images\base\health_inactive_male
MouseOverAction=!Execute [!ShowMeter ActiveUI][!ShowMeter ActiveSprite][!ShowMeter ActiveLabel][!ShowMeter ActiveMeterRAMBar][!ShowMeter ActiveMeterDigit100][!ShowMeter ActiveMeterDigit010][!ShowMeter ActiveMeterDigit001][!HideMeter MeterDigit100][!HideMeter MeterDigit010][!HideMeter MeterDigit001][!HideMeter MeterRAMBar][!HideMeter Sprite][!HideMeter UI][!HideMeter Label][!Update]

[ActiveUI]
Meter=Image
Hidden=1
ImageName=..\images\base\health_active_male
MouseLeaveAction=!Execute [!ShowMeter UI][!ShowMeter Sprite][!ShowMeter Label][!ShowMeter MeterRAMBar][!ShowMeter MeterDigit100][!ShowMeter MeterDigit010][!ShowMeter MeterDigit001][!HideMeter ActiveMeterDigit100][!HideMeter ActiveMeterDigit010][!HideMeter ActiveMeterDigit001][!HideMeter ActiveMeterRAMBar][!HideMeter ActiveLabel][!HideMeter ActiveSprite][!HideMeter ActiveUI][!Update]

[Label]
Meter=Image
ImageName=..\images\labels\label_ram
x=62
y=10

[ActiveLabel]
Meter=Image
Hidden=1
ImageName=..\images\labels\label_ram
x=62
y=12
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[MeasureTotalRAM]
Measure=PhysicalMemory
Total=1

[MeasureUsedRAM]
Measure=PhysicalMemory

[MeasureRAM]
;Measure=PhysicalMemory
;InvertMeasure=1
;Processor=0
Measure=Calc
Formula=(MeasureUsedRAM / MeasureTotalRAM * 100)
UpdateDivider=1
IfCondition=(#CURRENTSECTION# >= 80)
IfTrueAction=[!SetOption MeterRAMBar ImageName "..\images\health_bars\percentage_20.png"][!SetOption ActiveMeterRAMBar ImageName "..\images\health_bars\percentage_20.png"][!UpdateMeter MeterRAMBar][!UpdateMeter ActiveMeterRAMBar][!Redraw]
IfCondition2=(#CURRENTSECTION# < 80) && (#CURRENTSECTION# >= 50)
IfTrueAction2=[!SetOption MeterRAMBar ImageName "..\images\health_bars\percentage_50.png"][!SetOption ActiveMeterRAMBar ImageName "..\images\health_bars\percentage_50.png"][!UpdateMeter MeterRAMBar][!UpdateMeter ActiveMeterRAMBar][!Redraw]
IfCondition3=(#CURRENTSECTION# < 50)
IfTrueAction3=[!SetOption MeterRAMBar ImageName "..\images\health_bars\percentage_100.png"][!SetOption ActiveMeterRAMBar ImageName "..\images\health_bars\percentage_100.png"][!UpdateMeter MeterRAMBar][!UpdateMeter ActiveMeterRAMBar][!Redraw]
DynamicVariables=1

[MeterRAMBar]
Meter=Image
X=192
Y=16
W=(100 - (100 * [MeasureRAM]/100))
H=6
DynamicVariables=1

[ReversedRAM]
Measure=Calc
Formula=(100 - [MeasureRAM])
;Formula=99.5
DynamicVariables=1

;*****************TEST*************
;[MeterRAM]
;Meter=String
;MeasureName=MeasureRAM
;Text="RAM Usage: %1%"
;x=40
;y=50

;[MeterReversedRAM]
;Meter=String
;MeasureName=ReversedRAM
;Text="RAM Usage: %1%"
;x=0r
;y=10r
;****************************

[ActiveMeterRAMBar]
Meter=Image
Hidden=1
X=192
Y=18
W=(100 - (100 * [MeasureRAM]/100))
H=6
DynamicVariables=1

[Digit100]
Measure=Calc
;Formula=Trunc([MeasureRAM]/100)
Formula=Floor([ReversedRAM]/100)
IfCondition=(#CURRENTSECTION# >= 1)
IfTrueAction=[!SetOption MeterDigit100 MeasureName "1"][!UpdateMeter MeterDigit100][!SetOption ActiveMeterDigit100 MeasureName "1"][!UpdateMeter ActiveMeterDigit100][!Redraw]
IfCondition2=(#CURRENTSECTION# < 1)
IfTrueAction2=[!SetOption MeterDigit100 MeasureName "blank"][!UpdateMeter MeterDigit100][!SetOption ActiveMeterDigit100 MeasureName "blank"][!UpdateMeter ActiveMeterDigit100][!Redraw]
DynamicVariables=1

[Digit010]
Measure=Calc
Formula=Floor(([ReversedRAM]-((Trunc([ReversedRAM]/100))*100))/10)
;Formula=Floor(([MeasureRAM]-((Trunc([MeasureRAM]/100))*100))/10)
IfCondition=(#CURRENTSECTION# < 1) && ([Digit100] < 1)
IfTrueAction=[!SetOption MeterDigit010 ImageName "blank"][!UpdateMeter MeterDigit010][!SetOption ActiveMeterDigit010 ImageName "blank"][!UpdateMeter ActiveMeterDigit010][!Redraw]
DynamicVariables=1

[Digit001]
Measure=Calc
;Formula=[MeasureRAM]%10
Formula=Floor([ReversedRAM]%10)
DynamicVariables=1

[MeterDigit100]
Meter=Image
MeasureName=Digit100
DynamicVariables=1
x=226
y=28

[MeterDigit010]
Meter=Image
MeasureName=Digit010
DynamicVariables=1
x=8r
y=0r

[MeterDigit001]
Meter=Image
MeasureName=Digit001
DynamicVariables=1
x=10r
y=0r

[ActiveMeterDigit100]
Meter=Image
Hidden=1
MeasureName=Digit100
DynamicVariables=1
x=226
y=30

[ActiveMeterDigit010]
Meter=Image
Hidden=1
MeasureName=Digit010
DynamicVariables=1
x=8r
y=0r

[ActiveMeterDigit001]
Meter=Image
Hidden=1
MeasureName=Digit001
DynamicVariables=1
x=10r
y=0r

;********************TESTS*************************

;[TestDigit100]
;Meter=String
;MeasureName=Digit100
;Text="Digit100: %1%"
;x=40
;y=50

;[TestDigit010]
;Meter=String
;MeasureName=Digit010
;Text="Digit010: %1%"
;x=0r
;y=10r

;[TestDigit001]
;Meter=String
;MeasureName=Digit001
;Text="Digit001: %1%"
;x=0r
;y=10r
;**************************************************

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;Sprite
[Sprite]
Meter=Image
ImageName=..\images\sprites\004_charmander_inactive.png
x=5
y=5
LeftMouseUpAction=["taskmgr.exe"]
ToolTipText=Left-click to open Task Manager

[ActiveSprite]
Meter=Image
Hidden=1
ImageName=..\images\sprites\004_charmander_active.png
x=6
y=6
LeftMouseUpAction=["taskmgr.exe"]
ToolTipText=Left-click to open Task Manager

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[Rainmeter]
Update=1000

[Metadata]
Author = Paulina triplepants