[Variables]
@include=#@#Variables.inc

[UI]
Meter=Image
ImageName=..\images\base\health_inactive_female
MouseOverAction=!Execute [!ShowMeter ActiveUI][!ShowMeter ActiveSprite][!ShowMeter ActiveLabel][!ShowMeter ActiveMeterCPUBar][!ShowMeter ActiveMeterDigit100][!ShowMeter ActiveMeterDigit010][!ShowMeter ActiveMeterDigit001][!HideMeter MeterDigit100][!HideMeter MeterDigit010][!HideMeter MeterDigit001][!HideMeter MeterCPUBar][!HideMeter Sprite][!HideMeter UI][!HideMeter Label][!Update]

[ActiveUI]
Meter=Image
Hidden=1
ImageName=..\images\base\health_active_female
MouseLeaveAction=!Execute [!ShowMeter UI][!ShowMeter Sprite][!ShowMeter Label][!ShowMeter MeterCPUBar][!ShowMeter MeterDigit100][!ShowMeter MeterDigit010][!ShowMeter MeterDigit001][!HideMeter ActiveMeterDigit100][!HideMeter ActiveMeterDigit010][!HideMeter ActiveMeterDigit001][!HideMeter ActiveMeterCPUBar][!HideMeter ActiveLabel][!HideMeter ActiveSprite][!HideMeter ActiveUI][!Update]

[Label]
Meter=Image
ImageName=..\images\labels\label_cpu
x=62
y=10

[ActiveLabel]
Meter=Image
Hidden=1
ImageName=..\images\labels\label_cpu
x=62
y=12
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[MeasureCPU]
Measure=CPU
Processor=0
IfCondition=(#CURRENTSECTION# >= 80)
IfTrueAction=[!SetOption MeterCPUBar ImageName "..\images\health_bars\percentage_20.png"][!SetOption ActiveMeterCPUBar ImageName "..\images\health_bars\percentage_20.png"][!UpdateMeter MeterCPUBar][!UpdateMeter ActiveMeterCPUBar][!Redraw]
IfCondition2=(#CURRENTSECTION# < 80) && (#CURRENTSECTION# >= 50)
IfTrueAction2=[!SetOption MeterCPUBar ImageName "..\images\health_bars\percentage_50.png"][!SetOption ActiveMeterCPUBar ImageName "..\images\health_bars\percentage_50.png"][!UpdateMeter MeterCPUBar][!UpdateMeter ActiveMeterCPUBar][!Redraw]
IfCondition3=(#CURRENTSECTION# < 50)
IfTrueAction3=[!SetOption MeterCPUBar ImageName "..\images\health_bars\percentage_100.png"][!SetOption ActiveMeterCPUBar ImageName "..\images\health_bars\percentage_100.png"][!UpdateMeter MeterCPUBar][!UpdateMeter ActiveMeterCPUBar][!Redraw]
DynamicVariables=1

[MeterCPUBar]
Meter=Image
X=192
Y=16
W=(100 - (100 * [MeasureCPU]/100))
H=6
DynamicVariables=1

[ReversedCPU]
Measure=Calc
Formula=(100 - [MeasureCPU])
;Formula=99.5
DynamicVariables=1

;*****************TEST*************
;[MeterCPU]
;Meter=String
;MeasureName=MeasureCPU
;Text="CPU Usage: %1%"
;x=40
;y=0

;[MeterReversedCPU]
;Meter=String
;MeasureName=ReversedCPU
;Text="CPU Usage: %1%"
;x=0r
;y=10r
;****************************

[ActiveMeterCPUBar]
Meter=Image
Hidden=1
X=192
Y=18
W=(100 - (100 * [MeasureCPU]/100))
H=6
DynamicVariables=1

[Digit100]
Measure=Calc
;Formula=Trunc([MeasureCPU]/100)
Formula=Floor([ReversedCPU]/100)
IfCondition=(#CURRENTSECTION# >= 1)
IfTrueAction=[!SetOption MeterDigit100 MeasureName "1"][!UpdateMeter MeterDigit100][!SetOption ActiveMeterDigit100 MeasureName "1"][!UpdateMeter ActiveMeterDigit100][!Redraw]
IfCondition2=(#CURRENTSECTION# < 1)
IfTrueAction2=[!SetOption MeterDigit100 MeasureName "blank"][!UpdateMeter MeterDigit100][!SetOption ActiveMeterDigit100 MeasureName "blank"][!UpdateMeter ActiveMeterDigit100][!Redraw]
DynamicVariables=1

[Digit010]
Measure=Calc
Formula=Floor(([ReversedCPU]-((Trunc([ReversedCPU]/100))*100))/10)
;Formula=Floor(([MeasureCPU]-((Trunc([MeasureCPU]/100))*100))/10)
IfCondition=(#CURRENTSECTION# < 1) && ([Digit100] < 1)
IfTrueAction=[!SetOption MeterDigit010 ImageName "blank"][!UpdateMeter MeterDigit010][!SetOption ActiveMeterDigit010 ImageName "blank"][!UpdateMeter ActiveMeterDigit010][!Redraw]
DynamicVariables=1

[Digit001]
Measure=Calc
;Formula=[MeasureCPU]%10
Formula=Floor([ReversedCPU]%10)
DynamicVariables=1

[MeterDigit100]
Meter=Image
MeasureName=Digit100
DynamicVariables=1
x=226
y=28

[MeterDigit010]
Meter=Image
MeasureName=Digit010
DynamicVariables=1
x=8r
y=0r

[MeterDigit001]
Meter=Image
MeasureName=Digit001
DynamicVariables=1
x=10r
y=0r

[ActiveMeterDigit100]
Meter=Image
Hidden=1
MeasureName=Digit100
DynamicVariables=1
x=226
y=30

[ActiveMeterDigit010]
Meter=Image
Hidden=1
MeasureName=Digit010
DynamicVariables=1
x=8r
y=0r

[ActiveMeterDigit001]
Meter=Image
Hidden=1
MeasureName=Digit001
DynamicVariables=1
x=10r
y=0r

;********************TESTS*************************

;[TestDigit100]
;Meter=String
;MeasureName=Digit100
;Text="Digit100: %1%"
;x=40
;y=50

;[TestDigit010]
;Meter=String
;MeasureName=Digit010
;Text="Digit010: %1%"
;x=0r
;y=10r

;[TestDigit001]
;Meter=String
;MeasureName=Digit001
;Text="Digit001: %1%"
;x=0r
;y=10r
;**************************************************

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;Sprite
[Sprite]
Meter=Image
ImageName=..\images\sprites\001_bulbasaur_inactive.png
x=5
y=5
LeftMouseUpAction=["taskmgr.exe"]
ToolTipText=Left-click to open Task Manager

[ActiveSprite]
Meter=Image
Hidden=1
ImageName=..\images\sprites\001_bulbasaur_active.png
x=6
y=6
LeftMouseUpAction=["taskmgr.exe"]
ToolTipText=Left-click to open Task Manager

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[Rainmeter]
Update=1000

[Metadata]
Author = Paulina triplepants